apiVersion: v1
kind: Service
metadata:
  name: fast-api
spec:
  selector:
    app.kubernetes.io/name: fast-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 #incoming traffic in 80 is forwarded to port 80